# Generated by Django 5.1.2 on 2024-10-12 11:33

from django.db import migrations, models


def default_app_settings(apps, schema_editor):
    AppSettings = apps.get_model('user', 'AppSettings')
    AppSettings.objects.create(request_count=0)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RunPython(default_app_settings)
    ]
